### ISSUE TITLE
You must override the `supportedEvents` method of UnityPlayTs

### ISSUE THREAD

**Issue by Nuengnakhap** [azesmway/react-native-unity-play-ts#2]
I got this error when I run unity on app.
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/31353598/160627027-46abc7b1-5221-44ac-8deb-b3233614a875.png">

**Comment by azesmway** [comment]
Deleted by mistake, add to file UnityPlayTs.m

```
- (NSArray<NSString *> *)supportedEvents {
    return @[@"onUnityMessage"];
}
```
