### ISSUE TITLE
NSMutableDictonary cannot be converted to NSString

### ISSUE THREAD

**Issue by Nuengnakhap** [azesmway/react-native-unity-play-ts#3]
I got this error when I use postMessage

JSON value '{
    gameObject = "Server Connection";
    message = "API_PATH";
    methodName = SetupEndpoint;
}' of type NSMutableDictionary cannot be converted to NSString

+[RCTConvert NSString:]
    RCTConvert.m:59
__41-[RCTModuleMethod processMethodSignature]_block_invoke_16
__41-[RCTModuleMethod processMethodSignature]_block_invoke.164
-[RCTModuleMethod invokeWithBridge:module:arguments:]
-[RCTUIManager dispatchViewManagerCommand:commandID:commandArgs:]
D2716F2F-688B-3D51-BA8B-17E6553B209E
D2716F2F-688B-3D51-BA8B-17E6553B209E
D2716F2F-688B-3D51-BA8B-17E6553B209E
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
69DAC9C7-DDAF-318E-B068-BE596D142A2F
69DAC9C7-DDAF-318E-B068-BE596D142A2F
69DAC9C7-DDAF-318E-B068-BE596D142A2F
69DAC9C7-DDAF-318E-B068-BE596D142A2F
69DAC9C7-DDAF-318E-B068-BE596D142A2F
_pthread_wqthread
start_wqthread

**Comment by azesmway** [comment]
I change readme

use 
```
unityRef.current.postMessage(message.gameObject, message.methodName, message.message);
```

**Comment by Nuengnakhap** [comment]
Ok, Thank you
